sudo: false
language: python
#install: pip install tox-travis
#script: ./.travis.sh
env:
  - TOXENV=py27
  - TOXENV=pep8
  - TOXENV=pylint
  - TOXENV=docs
  - TOXENV=codacy-coverage-upload TOX_TESTENV_PASSENV=CODACY_PROJECT_TOKEN
#  - TOXENV=js
install: pip install tox-travis
script: tox

# This awfulness is so we can run tests under xvfb
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
