sudo: false
language: python
#install: pip install tox-travis
#script: ./.travis.sh
env:
  - TOXENV=py27
  - TOXENV=pycover
  - TOXENV=pep8
  - TOXENV=pylint
  - TOXENV=docs
  - TOXENV=codacy-coverage-upload TOX_TESTENV_PASSENV=CODACY_PROJECT_TOKEN
  - TOXENV=codacy-coverage-upload-js TOX_TESTENV_PASSENV=CODACY_PROJECT_TOKEN
  - TOXENV=js
  - TOXENV=jscover
  - TOXENV=js
install: 
  - pip install tox-travis
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install
script: tox

# This awfulness is so we can run tests under xvfb
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
