sudo: false
language: python
#install: pip install tox-travis
#script: ./.travis.sh
env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=pep8
  - TOXENV=pylint
  - TOXENV=docs
  - TOXENV=codacy-coverage-upload
install: pip install tox-travis
script: tox

