sudo: false
language: python
# When updating, don't forget tox.ini
# Not supported (yet)
#  - "3.4"
#  - "3.5"
env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=pep8
  - TOXENV=pep8
  - TOXENV=pylint
  - TOXENV=docs
install: pip install tox-travis
script: tox
before_install:
  - pip install codecov
after_success:
  - codecov
