sudo: false
language: python
#install: pip install tox-travis
#script: ./.travis.sh
env:
  - TOXENV=py27
  - TOXENV=pep8
  - TOXENV=pylint
  - TOXENV=docs
  - TOXENV=codacy-coverage-upload TOX_TESTENV_PASSENV=CODACY_PROJECT_TOKEN
install: pip install tox-travis
script: tox

